Repository openrewrite/rewrite-micronaut, pull requests merged in 2023-07, with the labels that each got.

#65 Update Micronaut Data transactions to jakarta.transactional.
  build.gradle.kts
  src/main/resources/META-INF/rewrite/classpath/jakarta.transaction-api-2.0.1.jar
  src/main/resources/META-INF/rewrite/classpath/javax.transaction-api-1.3.jar
  src/main/resources/META-INF/rewrite/classpath/micronaut-data-jdbc-4.0.0-M15.jar
  src/main/resources/META-INF/rewrite/micronaut3-to-4.yml
  src/test/java/org/openrewrite/java/micronaut/UpdateMicronautDataTransactionsTest.java
Labels: recipe

#66 Update usage of TaskExecutors.IO to TaskExecutors.BLOCKING
  src/main/resources/META-INF/rewrite/micronaut3-to-4.yml
  src/test/java/org/openrewrite/java/micronaut/UpdateTaskExecutorsTest.java
Labels: recipe

#70 Remove withJansi from logback configuration.
  src/main/resources/META-INF/rewrite/micronaut3-to-4.yml
  src/test/java/org/openrewrite/java/micronaut/RemoveWithJansiLogbackConfigurationTest.java
Labels: recipe

#72 Ensure Gradle wrapper doesn't get added to Maven projects.
  src/main/resources/META-INF/rewrite/micronaut3-to-4.yml
Labels: bug

#69 Revise approach to upgrading Micronaut Validation.
  src/main/java/org/openrewrite/java/micronaut/AddAnnotationProcessorPath.java
  src/main/resources/META-INF/rewrite/micronaut3-to-4.yml
  src/test/java/org/openrewrite/java/micronaut/UpdateMicronautValidationTest.java
Labels: recipe

#80 Remove unnecessary micronaut-runtime dependency.
  src/main/java/org/openrewrite/java/micronaut/MicronautVersionHelper.java
  src/main/resources/META-INF/rewrite/micronaut3-to-4.yml
  src/test/java/org/openrewrite/java/micronaut/RemoveUnnecessaryDependenciesTest.java
Labels: bug

#82 Add HttpRequest type parameter for various Micronaut Security interfaces.
  build.gradle.kts
  src/main/java/org/openrewrite/java/micronaut/AddHttpRequestTypeParameter.java
  src/main/resources/META-INF/rewrite/classpath/micronaut-http-4.0.0.jar
  src/main/resources/META-INF/rewrite/classpath/micronaut-security-4.0.0.jar
  src/main/resources/META-INF/rewrite/classpath/micronaut-security-jwt-4.0.0.jar
  src/main/resources/META-INF/rewrite/classpath/micronaut-security-oauth2-4.0.0.jar
  src/main/resources/META-INF/rewrite/micronaut3-to-4.yml
  src/test/java/org/openrewrite/java/micronaut/AddHttpRequestTypeParameterTest.java
Labels: recipe

#87 Remove old annotation processor path for Micronaut Validation.
  src/main/java/org/openrewrite/java/micronaut/RemoveAnnotationProcessorPath.java
  src/main/resources/META-INF/rewrite/micronaut3-to-4.yml
  src/test/java/org/openrewrite/java/micronaut/UpdateMicronautValidationTest.java
Labels: recipe

#88 Update version for core annotation processors in pom.xml
  src/main/resources/META-INF/rewrite/micronaut3-to-4.yml
  src/test/java/org/openrewrite/java/micronaut/UpdateMavenAnnotationProcessorsTest.java
Labels: recipe

#91 Correctly apply version when executed by Maven plugin.
  src/main/java/org/openrewrite/java/micronaut/AddAnnotationProcessorPath.java
  src/main/java/org/openrewrite/java/micronaut/ChangeAnnotationProcessorPath.java
  src/main/java/org/openrewrite/java/micronaut/MavenExclusions.java
  src/main/resources/META-INF/rewrite/micronaut3-to-4.yml
  src/test/java/org/openrewrite/java/micronaut/UpdateMavenAnnotationProcessorsTest.java
Labels: bug, enhancement

#94 Add micronaut-inject exclusion to non-core annotation processors.
  src/main/java/org/openrewrite/java/micronaut/ChangeAnnotationProcessorPath.java
  src/main/resources/META-INF/rewrite/micronaut3-to-4.yml
  src/test/java/org/openrewrite/java/micronaut/UpdateMavenAnnotationProcessorsTest.java
Labels: enhancement

#95 Adopt new J.Identifier constructors
  src/main/java/org/openrewrite/java/micronaut/AddHttpRequestTypeParameter.java
  src/main/java/org/openrewrite/java/micronaut/FixDeprecatedExceptionHandlerConstructors.java
  src/main/java/org/openrewrite/java/micronaut/OncePerRequestHttpServerFilterToHttpServerFilter.java
  src/main/java/org/openrewrite/java/micronaut/SubclassesReturnedFromFactoriesNotInjectable.java
Labels: enhancement
